### PR TITLE
Update pod source to https://github.com/tumblr/JXHTTP.git

### PR DESCRIPTION
**Pull request by eladb**
If you could please also republish the pod to Cocoapods. Right now, the tumblr pod cannot be installed.

### CODE REVIEW

**Comment by eladb** [comment]
@irace can you assist?

**Comment by irace** [comment]
@eladb What problem are you currently having?

**Comment by eladb** [comment]
It seems like pod is published under the `tumblr` account while the pod spec links to the `jstn` account. In the past the `jstn` account was not available and the pod installation failed. Now it seems like it's available but I would recommend aligning the repo URL and the actual pod spec.

**Comment by irace** [comment]
If it's currently working for you, I'm going to leave it. If not, I'll try and fix it for you. We will hopefully be transitioning to AFNetworking sometime relatively soon. Thanks for your help!

**Comment by eladb** [comment]
OK. No problem.

**Comment by eladb** [comment]
Why `AFNetworking` if I may ask? `NSURLSession` pretty much covers most of the bases for me...

**Comment by irace** [comment]
@eladb Possible that I will end up using just `NSURLSession` directly but we use multipart file uploads for example, which AFNetworking has nice support for out of the box.

**Comment by eladb** [comment]
Yes, that's probably the only thing I use it for too... But then I hand off the `NSURLRequest` to `NSURLSession` :-)

**Comment by apbendi** [comment]
Is it possible to update the podspecs for older versions of JXHTTP (which are required for users who might still be on an older version of the Tumblr SDK)? For example:

https://github.com/CocoaPods/Specs/blob/master/Specs/JXHTTP/1.0.3/JXHTTP.podspec.json#L11

Everything before 2.0.2 points to `https://github.com/jstn/JXHTTP.git`. The older versions are still available, they've just been moved to `https://github.com/tumblr/JXHTTP.git`. This would be very helpful. Thanks!

**Comment by irace** [comment]
@apbendi Attempting to do this for you: https://github.com/CocoaPods/Specs/pull/13193

**Comment by apbendi** [comment]
@irace :hand: :raised_hands: Thanks a lot, big help!

**Pull request closed without merging**
